# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "tumblr-sync"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vincent Durand"]
  s.date = "2012-11-02"
  s.description = "Synchronize pictures from a Thumblr blog, with multithreading"
  s.email = "vincent.durand@madwork.org"
  s.executables = ["tumblr-sync"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/tumblr-sync",
    "lib/tumblr-sync.rb",
    "lib/tumblr-sync/runner.rb",
    "lib/tumblr-sync/site.rb",
    "test/helper.rb",
    "test/test_tumblr-sync.rb",
    "tumblr-sync.gemspec"
  ]
  s.homepage = "http://github.com/madwork/tumblr-sync"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Synchronize pictures from a Thumblr blog"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mechanize>, ["~> 2.5.1"])
      s.add_runtime_dependency(%q<ruby-progressbar>, ["~> 1.0.2"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.8.3"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<mechanize>, ["~> 2.5.1"])
      s.add_dependency(%q<ruby-progressbar>, ["~> 1.0.2"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.8.3"])
      s.add_dependency(%q<bundler>, ["~> 1.2.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<mechanize>, ["~> 2.5.1"])
    s.add_dependency(%q<ruby-progressbar>, ["~> 1.0.2"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.8.3"])
    s.add_dependency(%q<bundler>, ["~> 1.2.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

